In [17]:
import pandas as pd

df = pd.read_csv("../dataset/IMDB Dataset.csv")

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
##Converte os sentimentos para números
df["sentiment"] = df["sentiment"].map({
    "positive": 1,
    "negative": 0
})

df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [ ]:
##Separa as entradas e saidas, os comentarios de positivo/negativo
X = df["review"]
y = df["sentiment"]

print(X.shape)
print(y.shape)

(50000,)
(50000,)

In [ ]:
##Transforma textos em números, identificando as palavras mais relevantes
from sklearn.feature_extraction.text import TfidfVectorizer 

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

X_tfidf = vectorizer.fit_transform(X)

print(X_tfidf.shape)



##O resultado retornou 50000 avaliações para 5000 palavras mais relevantes

(50000, 5000)

In [ ]:
##Serpara a quantidade de treino e de teste, com base na quantidade que definimos (0,2 para teste)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42
)


print("Treino:", X_train.shape)
print("Teste:", X_test.shape)

Treino: (40000, 5000)
Teste: (10000, 5000)